import = [
    "~/dotfiles/config/alacritty/themes/theme.toml"
]

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Regular"

[font.italic]
style = "Regular"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001&"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001-"
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001|"
key = "E"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001s"
key = "G"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001m"
key = "M"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001n"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001p"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Super|Shift"

[scrolling]
history = 100000

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 0.9
