[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Regular"

[font.italic]
style = "Regular"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001&"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001-"
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001|"
key = "E"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001s"
key = "G"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001m"
key = "M"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001n"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001p"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Super|Shift"

[scrolling]
history = 100000

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 0.9
