#!/bin/bash
OS=$(uname -s)
ACCOUNT=$1
ITEM=$2

if [ "x$ACCOUNT" = "x" ]; then
  echo "Please inform the account name"
  exit 1
fi

if [ "x$ITEM" = "x" ]; then
  echo "Please inform the security item to be retrieved"
  exit 1
fi

if [ "$OS" = "Darwin" ]; then
  # Store with:
  # security add-generic-password -a email@account.com -s mail -w MyPaSsWorD
  security find-generic-password -a $ACCOUNT -s $ITEM -w
elif [ "$OS" = "Linux" ]; then
  # Store with:
  # secret-tool store --label=credential email@account.com mail
  # then input the password
  secret-tool lookup $ACCOUNT $ITEM
else
  echo "OS not supported"
  exit 1
fi
