#!/bin/bash
OS=$(uname -s)

# Ensure tmp directory is present
TMP_DIR=$HOME/.mutt/attachments/
mkdir $TMP_DIR || true

# Copy file to tmp location to have it available after mutt removes it.
FILE=$TMP_DIR/$(basename $1)
cp $1 $FILE

if [ "$OS" = "Darwin" ]; then
  open $FILE
#  rm $FILE
elif [ "$OS" = "Linux" ]; then
  # TODO
  exit 1
else
  echo "OS not supported"
  exit 1
fi
