[".config/nvim"]
type = "git-repo"
url = "https://github.com/jeduardo/nvim"
refreshPeriod = "1h"

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "24h"

[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
refreshPeriod = "24h"


[".local/bin/lpass"]
url = "https://github.com/jeduardo/lastpass-rs/releases/latest/download/lpass-{{ if eq .chezmoi.os "darwin" }}macos{{ else }}linux{{ end }}-{{ if eq .chezmoi.arch "amd64" }}x86_64{{ else }}{{ .chezmoi.arch }}{{ end }}.tar.gz"
path = "lpass-{{ if eq .chezmoi.os "darwin" }}macos{{ else }}linux{{ end }}-{{ if eq .chezmoi.arch "amd64" }}x86_64{{ else }}{{ .chezmoi.arch }}{{ end }}"
type = "archive-file"
executable = true
refreshPeriod = "24h"
