[".config/nvim"]
type = "git-repo"
url = "https://github.com/jeduardo/nvim"
refreshPeriod = "1h"

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "24h"

[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
refreshPeriod = "24h"
