#!/bin/bash

# Brightness control level script

NOTIFY=/usr/bin/notify-send
TITLE=Brightness
XRANDR=/usr/bin/xrandr
GREP=/bin/grep
WC=/usr/bin/wc
BC=/usr/bin/bc
CUT=/usr/bin/cut
SED=/bin/sed
STEPS=40
FUNC=$1

if [ "x$FUNC" == "x" ]; then
  echo "$0 <inc|dec>"
  exit 1
fi

MAX_LINES=$($XRANDR | $WC -l)

# Run through all connected displays
for screenname in $($XRANDR --verbose | grep " connected" | $CUT -f1 -d" "); do
  # Get current backlight 
  BACKLIGHT=$($XRANDR --verbose | $GREP BACKLIGHT | $CUT -d ':' -f 2 | $SED 's/^[[:space:]]*//')
  # Get brightness ranges for the display being processed
  LIMITS=$($XRANDR --verbose | $GREP -A $MAX_LINES $screenname | $GREP -A 1 BACKLIGHT | $GREP range | $CUT -d : -f 2 | tr '()' ' ')
  LOWER_LIMIT=$(echo $LIMITS | $CUT -d , -f 1)
  UPPER_LIMIT=$(echo $LIMITS | $CUT -d , -f 2 | $SED 's/^[[:space:]]*//')
  # Calculate new brightness value
  if [ "$FUNC" == "inc" ]; then
    NEW_BACKLIGHT=$($BC <<< "scale=0; $BACKLIGHT + $UPPER_LIMIT / $STEPS")
  elif [ "$FUNC" == "dec" ]; then
    NEW_BACKLIGHT=$($BC <<< "scale=0; $BACKLIGHT - $UPPER_LIMIT / $STEPS")
  fi
  # Wrap values around boundaries
  if (( $NEW_BACKLIGHT < 0 )); then
    NEW_BACKLIGHT=0
  elif (( $NEW_BACKLIGHT > $UPPER_LIMIT )); then
    NEW_BACKLIGHT=$UPPER_LIMIT 
  fi
  # Apply new backlight
  $XRANDR --output $screenname --set BACKLIGHT $NEW_BACKLIGHT
  # Calculate percentage
  PERCENTAGE=$($BC <<< "scale=0; 100 * $NEW_BACKLIGHT / $UPPER_LIMIT")
  MSG="[info]: Screen Brightness level on ${screenname} set to ${PERCENTAGE}%"
  echo $MSG
  $NOTIFY $TITLE "$MSG"
done
