#!/bin/bash

# Bash script to control the monitor brightness
# Source:
# http://sandipbgt.com/2015/10/01/control-screen-brightness-from-commandline-in-ubuntu/


SYNTAX="\\n \\t SYNTAX:  dimmer level \\n \\t Where 'level' ranges from 0 to 100.\\n";

FUNC=$1
PERCENTAGE=$2

NOTIFY=/usr/bin/notify-send
TITLE=Brightness

# If no level was specified, then get the current brightness and change nothing.
# awk multiplication thanks to
# https://www.linuxquestions.org/questions/linux-software-2/multiply-floats-in-bash-script-618691/
if [ "x$LEVEL" == "x" ]; then
  LEVEL="$(xrandr --verbose | grep -i brightness | head -1 | cut -d ':' -f 2 | tr -d '[:space:]')"
  LEVEL="$(echo $LEVEL 100 | awk '{printf "%4.0f\n",$1*$2}')"
fi

case $FUNC in
  "inc")
    LEVEL=$(($LEVEL + $PERCENTAGE))
    ;;
  "dec")
    LEVEL=$(($LEVEL - $PERCENTAGE))
    ;;
esac

if [ $LEVEL -gt 100 ]; then
    echo -e $SYNTAX;
    exit 1;
fi

if [ $LEVEL -lt 0 ]; then
    echo -e $SYNTAX;
    exit 1;
fi
brightness_level="$(( $LEVEL / 100)).$(( $LEVEL % 100 ))"
for screenname in $(xrandr | grep " connected" | cut -f1 -d" "); do
    xrandr --output $screenname --brightness $brightness_level;
    MSG="[info]: Screen Brightness level on ${screenname} set to ${LEVEL}%"
    echo $MSG
    $NOTIFY $TITLE "$MSG"
done
