#!/bin/bash

# For whatever reason it doesn't work if I use the full name
# intel-virtual-output
INTEL_PROCESS=intel-virtual
PGREP=/usr/bin/pgrep
PKILL=/usr/bin/pkill
PS=/bin/ps
XRANDR=/usr/bin/xrandr
FEH=/usr/bin/feh

$PGREP -U $USER $INTEL_PROCESS > /dev/null
if (($? == 0)); then
  # Intel virtual output is running
  $PS a | grep 'Xorg :8' >/dev/null
  if (($? == 0)); then
    #  Optimus X server is running
    echo 'External display is ON, switching it off'
    $PKILL -U $USER $INTEL_PROCESS &&
    echo 'External display is now OFF'
  fi
else
  echo 'External display is OFF, switching it on'
  $INTEL_PROCESS-output &&
  $XRANDR --output VIRTUAL1 --mode VIRTUAL1.447-2560x1440 --above eDP1 &&
  $FEH --bg-scale ~/.i3background
  echo 'External display is now ON'
fi
