#!/bin/bash
VALUE=$(cat /sys/class/leds/smc::kbd_backlight/brightness)
INCREMENT=$2
TOTAL=unset

case $1 in
inc)
    TOTAL=`expr $VALUE + $INCREMENT`
    ;;
dec)
    TOTAL=`expr $VALUE - $INCREMENT`
    ;;
full)
    TOTAL=255
    ;;
off)
    TOTAL=0
    ;;
esac

if [ $TOTAL == unset ]; then
    echo "Please specify inc, dec, full, or off"
    exit 1
fi

if [ $TOTAL -gt 255 ]; then TOTAL=255; fi
if [ $TOTAL -lt 0 ]; then TOTAL=0; fi 
echo $TOTAL | sudo tee -a  /sys/class/leds/smc::kbd_backlight/brightness
